maybe fixed release version but whatever i dont care anymore

diff --git a/scripts/setlocalversion b/scripts/setlocalversion
--- a/scripts/setlocalversion
+++ b/scripts/setlocalversion
@@ -132,7 +132,7 @@ scm_version()
 
 collect_files()
 {
-	local file res
+	local file res=
 
 	for file; do
 		case "$file" in
@@ -158,7 +158,7 @@ fi
 if test -e include/config/auto.conf; then
 	. include/config/auto.conf
 else
-	echo "Error: kernelrelease not valid - run 'make prepare' to update it"
+	echo "Error: kernelrelease not valid - run 'make prepare' to update it" >&2
 	exit 1
 fi
 
@@ -174,17 +174,16 @@ res="${res}${CONFIG_LOCALVERSION}${LOCALVERSION}"
 # scm version string if not at a tagged commit
 if test "$CONFIG_LOCALVERSION_AUTO" = "y"; then
 	# full scm version string
-	res="$res$(scm_version)"
-fi
-#else
+	res="$res"
+else
 	# append a plus sign if the repository is not in a clean
 	# annotated or signed tagged state (as git describe only
 	# looks at signed or annotated tags - git tag -a/-s) and
 	# LOCALVERSION= is not specified
-	#if test "${LOCALVERSION+set}" != "set"; then
-	#	scm=$(scm_version --short)
-	#	res="$res${scm:++}"
-	#fi
-#fi
+	if test "${LOCALVERSION+set}" != "set"; then
+		scm=$(scm_version --short)
+		res="$res"
+	fi
+fi
 
 echo "$res"
